=== raycast/extensions/extensions/youversion-suggest/assets/data/schemas/schema-bible.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Bible data for a specific language",
  "type": "object",
  "properties": {
    "books": {
      "description": "The list of Bible books available in this language",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "The ID used by YouVersion to uniquely identify this book",
            "type": "string",
            "pattern": "^([a-z]{3}|[1-3][a-z]{2})$"
          },
          "name": {
            "description": "The name of this book in the respective language",
            "type": "string"
          }
        },
        "required": ["id", "name"],
        "additionalProperties": false
      }
    },
    "language": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The ISO 639-3 code for this language",
          "type": "string",
          "pattern": "^[a-z]{3}(_[a-z]{2,3})?$"
        },
        "name": {
          "description": "The name of this language as written in said language",
          "type": "string"
        }
      }
    },
    "default_version": {
      "description": "The default Bible version to use for this language",
      "type": "integer",
      "minimum": 1
    },
    "versions": {
      "description": "The list of Bible versions for this language",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "full_name": {
            "description": "The full, unabbreviated name of this version",
            "type": "string"
          },
          "id": {
            "description": "The ID used by YouVersion to uniquely identify this version",
            "type": "integer",
            "minimum": 1
          },
          "name": {
            "description": "The acronym for this version",
            "type": "string"
          }
        },
        "required": ["id", "name"],
        "additionalProperties": false
      }
    }
  },
  "required": ["books", "default_version", "versions"],
  "additionalProperties": false
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-ind.json
{
  "books": [
    {
      "id": "gen",
      "name": "Kejadian"
    },
    {
      "id": "exo",
      "name": "Keluaran"
    },
    {
      "id": "lev",
      "name": "Imamat"
    },
    {
      "id": "num",
      "name": "Bilangan"
    },
    {
      "id": "deu",
      "name": "Ulangan"
    },
    {
      "id": "jos",
      "name": "Yosua"
    },
    {
      "id": "jdg",
      "name": "Hakim-hakim"
    },
    {
      "id": "rut",
      "name": "Rut"
    },
    {
      "id": "1sa",
      "name": "1 Samuel"
    },
    {
      "id": "2sa",
      "name": "2 Samuel"
    },
    {
      "id": "1ki",
      "name": "1 Raja-raja"
    },
    {
      "id": "2ki",
      "name": "2 Raja-raja"
    },
    {
      "id": "1ch",
      "name": "1 Tawarikh"
    },
    {
      "id": "2ch",
      "name": "2 Tawarikh"
    },
    {
      "id": "ezr",
      "name": "Ezra"
    },
    {
      "id": "neh",
      "name": "Nehemia"
    },
    {
      "id": "est",
      "name": "Ester"
    },
    {
      "id": "job",
      "name": "Ayub"
    },
    {
      "id": "psa",
      "name": "Mazmur"
    },
    {
      "id": "pro",
      "name": "Amsal"
    },
    {
      "id": "ecc",
      "name": "Pengkhotbah"
    },
    {
      "id": "sng",
      "name": "Kidung Agung"
    },
    {
      "id": "isa",
      "name": "Yesaya"
    },
    {
      "id": "jer",
      "name": "Yeremia"
    },
    {
      "id": "lam",
      "name": "Ratapan"
    },
    {
      "id": "ezk",
      "name": "Yehezkiel"
    },
    {
      "id": "dan",
      "name": "Daniel"
    },
    {
      "id": "hos",
      "name": "Hosea"
    },
    {
      "id": "jol",
      "name": "Y\"oel"
    },
    {
      "id": "amo",
      "name": "Amos"
    },
    {
      "id": "oba",
      "name": "Obaja"
    },
    {
      "id": "jon",
      "name": "Yunus"
    },
    {
      "id": "mic",
      "name": "Mikha"
    },
    {
      "id": "nam",
      "name": "Nahum"
    },
    {
      "id": "hab",
      "name": "Habakuk"
    },
    {
      "id": "zep",
      "name": "Zefanya"
    },
    {
      "id": "hag",
      "name": "Hagai"
    },
    {
      "id": "zec",
      "name": "Zakharia"
    },
    {
      "id": "mal",
      "name": "Maleakhi"
    },
    {
      "id": "mat",
      "name": "Matius"
    },
    {
      "id": "mrk",
      "name": "Markus"
    },
    {
      "id": "luk",
      "name": "Lukas"
    },
    {
      "id": "jhn",
      "name": "Yohanes"
    },
    {
      "id": "act",
      "name": "Kisah Para Rasul"
    },
    {
      "id": "rom",
      "name": "Roma"
    },
    {
      "id": "1co",
      "name": "1 Korintus"
    },
    {
      "id": "2co",
      "name": "2 Korintus"
    },
    {
      "id": "gal",
      "name": "Galatia"
    },
    {
      "id": "eph",
      "name": "Efesus"
    },
    {
      "id": "php",
      "name": "Filipi"
    },
    {
      "id": "col",
      "name": "Kolose"
    },
    {
      "id": "1th",
      "name": "1 Tesalonika"
    },
    {
      "id": "2th",
      "name": "2 Tesalonika"
    },
    {
      "id": "1ti",
      "name": "1 Timotius"
    },
    {
      "id": "2ti",
      "name": "2 Timotius"
    },
    {
      "id": "tit",
      "name": "Titus"
    },
    {
      "id": "phm",
      "name": "Filemon"
    },
    {
      "id": "heb",
      "name": "Ibrani"
    },
    {
      "id": "jas",
      "name": "Yakobus"
    },
    {
      "id": "1pe",
      "name": "1 Petrus"
    },
    {
      "id": "2pe",
      "name": "2 Petrus"
    },
    {
      "id": "1jn",
      "name": "1 Yohanes"
    },
    {
      "id": "2jn",
      "name": "2 Yohanes"
    },
    {
      "id": "3jn",
      "name": "3 Yohanes"
    },
    {
      "id": "jud",
      "name": "Yudas"
    },
    {
      "id": "rev",
      "name": "Wahyu"
    }
  ],
  "default_version": 306,
  "language": {
    "id": "ind",
    "name": "Bahasa Indonesia"
  },
  "versions": [
    {
      "full_name": "Alkitab dalam Bahasa Indonesia Masa Kini",
      "id": 27,
      "name": "BIMK"
    },
    {
      "full_name": "Perjanjian Baru: Versi Mudah Dibaca",
      "id": 199,
      "name": "AMD"
    },
    {
      "full_name": "Alkitab Terjemahan Baru",
      "id": 306,
      "name": "TB"
    },
    {
      "full_name": "Terjemahan Sederhana Indonesia",
      "id": 320,
      "name": "TSI"
    },
    {
      "full_name": "Firman Allah Yang Hidup",
      "id": 2727,
      "name": "FAYH"
    },
    {
      "full_name": "Alkitab Terjemahan Lama",
      "id": 2861,
      "name": "LAI-TL"
    },
    {
      "full_name": "Indonesian Tazi NT Study Bible",
      "id": 2862,
      "name": "INOTAZI"
    },
    {
      "full_name": "Perjanjian Baru Terjemahan Baru Edisi 2",
      "id": 2863,
      "name": "PBTB2"
    }
  ]
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-spa.json
{
  "books": [
    {
      "id": "gen",
      "name": "Génesis"
    },
    {
      "id": "exo",
      "name": "Éxodo"
    },
    {
      "id": "lev",
      "name": "Levítico"
    },
    {
      "id": "num",
      "name": "Números"
    },
    {
      "id": "deu",
      "name": "Deuteronomio"
    },
    {
      "id": "jos",
      "name": "Josué"
    },
    {
      "id": "jdg",
      "name": "Jueces"
    },
    {
      "id": "rut",
      "name": "Rut"
    },
    {
      "id": "1sa",
      "name": "1 Samuel"
    },
    {
      "id": "2sa",
      "name": "2 Samuel"
    },
    {
      "id": "1ki",
      "name": "1 Reyes"
    },
    {
      "id": "2ki",
      "name": "2 Reyes"
    },
    {
      "id": "1ch",
      "name": "1 Crónicas"
    },
    {
      "id": "2ch",
      "name": "2 Crónicas"
    },
    {
      "id": "ezr",
      "name": "Esdras"
    },
    {
      "id": "neh",
      "name": "Nehemías"
    },
    {
      "id": "est",
      "name": "Ester"
    },
    {
      "id": "job",
      "name": "Job"
    },
    {
      "id": "psa",
      "name": "Salmo"
    },
    {
      "id": "pro",
      "name": "Proverbios"
    },
    {
      "id": "ecc",
      "name": "Eclesiastés"
    },
    {
      "id": "sng",
      "name": "Cantares"
    },
    {
      "id": "isa",
      "name": "Isaías"
    },
    {
      "id": "jer",
      "name": "Jeremías"
    },
    {
      "id": "lam",
      "name": "Lamentaciones"
    },
    {
      "id": "ezk",
      "name": "Ezequiel"
    },
    {
      "id": "dan",
      "name": "Daniel"
    },
    {
      "id": "hos",
      "name": "Oseas"
    },
    {
      "id": "jol",
      "name": "Joel"
    },
    {
      "id": "amo",
      "name": "Amós"
    },
    {
      "id": "oba",
      "name": "Abdías"
    },
    {
      "id": "jon",
      "name": "Jonás"
    },
    {
      "id": "mic",
      "name": "Miqueas"
    },
    {
      "id": "nam",
      "name": "Nahúm"
    },
    {
      "id": "hab",
      "name": "Habacuc"
    },
    {
      "id": "zep",
      "name": "Sofonías"
    },
    {
      "id": "hag",
      "name": "Hageo"
    },
    {
      "id": "zec",
      "name": "Zacarías"
    },
    {
      "id": "mal",
      "name": "Malaquías"
    },
    {
      "id": "mat",
      "name": "Mateo"
    },
    {
      "id": "mrk",
      "name": "Marcos"
    },
    {
      "id": "luk",
      "name": "Lucas"
    },
    {
      "id": "jhn",
      "name": "Juan"
    },
    {
      "id": "act",
      "name": "Hechos"
    },
    {
      "id": "rom",
      "name": "Romanos"
    },
    {
      "id": "1co",
      "name": "1 Corintios"
    },
    {
      "id": "2co",
      "name": "2 Corintios"
    },
    {
      "id": "gal",
      "name": "Gálatas"
    },
    {
      "id": "eph",
      "name": "Efesios"
    },
    {
      "id": "php",
      "name": "Filipenses"
    },
    {
      "id": "col",
      "name": "Colosenses"
    },
    {
      "id": "1th",
      "name": "1 Tesalonicenses"
    },
    {
      "id": "2th",
      "name": "2 Tesalonicenses"
    },
    {
      "id": "1ti",
      "name": "1 Timoteo"
    },
    {
      "id": "2ti",
      "name": "2 Timoteo"
    },
    {
      "id": "tit",
      "name": "Tito"
    },
    {
      "id": "phm",
      "name": "Filemón"
    },
    {
      "id": "heb",
      "name": "Hebreos"
    },
    {
      "id": "jas",
      "name": "Santiago"
    },
    {
      "id": "1pe",
      "name": "1 Pedro"
    },
    {
      "id": "2pe",
      "name": "2 Pedro"
    },
    {
      "id": "1jn",
      "name": "1 Juan"
    },
    {
      "id": "2jn",
      "name": "2 Juan"
    },
    {
      "id": "3jn",
      "name": "3 Juan"
    },
    {
      "id": "jud",
      "name": "Judas"
    },
    {
      "id": "rev",
      "name": "Apocalipsis"
    }
  ],
  "default_version": 128,
  "language": {
    "id": "spa",
    "name": "Español (América Latina)"
  },
  "versions": [
    {
      "full_name": "La Palabra (versión hispanoamericana)",
      "id": 28,
      "name": "BLPH"
    },
    {
      "full_name": "Biblia Dios Habla Hoy",
      "id": 52,
      "name": "DHH94I"
    },
    {
      "full_name": "La Biblia de las Américas",
      "id": 89,
      "name": "LBLA"
    },
    {
      "full_name": "Nueva Biblia de las Américas",
      "id": 103,
      "name": "NBLA"
    },
    {
      "full_name": "Nueva Traducción Viviente",
      "id": 127,
      "name": "NTV"
    },
    {
      "full_name": "Nueva Versión Internacional - Español",
      "id": 128,
      "name": "NVI"
    },
    {
      "full_name": "Reina Valera Contemporánea",
      "id": 146,
      "name": "RVC"
    },
    {
      "full_name": "Reina-Valera Antigua",
      "id": 147,
      "name": "RVES"
    },
    {
      "full_name": "Biblia Reina Valera 1960",
      "id": 149,
      "name": "RVR1960"
    },
    {
      "full_name": "Biblia Reina Valera 1995",
      "id": 150,
      "name": "RVR95"
    },
    {
      "full_name": "Traducción en Lenguaje Actual",
      "id": 176,
      "name": "TLA"
    },
    {
      "full_name": "Traducción en Lenguaje Actual Interconfesional",
      "id": 178,
      "name": "TLAI"
    },
    {
      "full_name": "La Biblia: La Palabra de Dios para todos",
      "id": 197,
      "name": "PDT"
    },
    {
      "full_name": "La Biblia Hispanoamericana (Traducción Interconfesional, versión hispanoamericana)",
      "id": 222,
      "name": "BHTI"
    },
    {
      "full_name": "Biblia Dios Habla Hoy",
      "id": 411,
      "name": "DHH94PC"
    },
    {
      "full_name": "Nueva Biblia Viva",
      "id": 753,
      "name": "NBV"
    },
    {
      "full_name": "Biblia del Jubileo",
      "id": 1076,
      "name": "JBS"
    },
    {
      "full_name": "Biblia del Oso 1573",
      "id": 1715,
      "name": "BDO1573"
    },
    {
      "full_name": "Biblia Reina Valera 1909",
      "id": 1718,
      "name": "RVR09"
    },
    {
      "full_name": "Reina Valera Actualizada",
      "id": 1782,
      "name": "RVA2015"
    },
    {
      "full_name": "Dios Habla Hoy DK",
      "id": 1845,
      "name": "DHHDK"
    },
    {
      "full_name": "Dios habla Hoy Estándar 1994",
      "id": 1846,
      "name": "DHHS94"
    },
    {
      "full_name": "El Nuevo Testamento, Versión Biblia Libre",
      "id": 1952,
      "name": "VBL"
    },
    {
      "full_name": "La Santa Biblia, Nueva Versión Internacional Simplificada",
      "id": 2664,
      "name": "NVIS"
    }
  ]
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-nld.json
{
  "books": [
    {
      "id": "gen",
      "name": "Genesis"
    },
    {
      "id": "exo",
      "name": "Exodus"
    },
    {
      "id": "lev",
      "name": "Leviticus"
    },
    {
      "id": "num",
      "name": "Numeri"
    },
    {
      "id": "deu",
      "name": "Deuteronomium"
    },
    {
      "id": "jos",
      "name": "Jozua"
    },
    {
      "id": "jdg",
      "name": "Richteren"
    },
    {
      "id": "rut",
      "name": "Ruth"
    },
    {
      "id": "1sa",
      "name": "1 Samuël"
    },
    {
      "id": "2sa",
      "name": "2 Samuël"
    },
    {
      "id": "1ki",
      "name": "1 Koningen"
    },
    {
      "id": "2ki",
      "name": "2 Koningen"
    },
    {
      "id": "1ch",
      "name": "1 Kronieken"
    },
    {
      "id": "2ch",
      "name": "2 Kronieken"
    },
    {
      "id": "ezr",
      "name": "Ezra"
    },
    {
      "id": "neh",
      "name": "Nehemia"
    },
    {
      "id": "est",
      "name": "Esther"
    },
    {
      "id": "job",
      "name": "Job"
    },
    {
      "id": "psa",
      "name": "Psalmen"
    },
    {
      "id": "pro",
      "name": "Spreuken"
    },
    {
      "id": "ecc",
      "name": "Prediker"
    },
    {
      "id": "sng",
      "name": "Hooglied"
    },
    {
      "id": "isa",
      "name": "Jesaja"
    },
    {
      "id": "jer",
      "name": "Jeremia"
    },
    {
      "id": "lam",
      "name": "Klaagliederen"
    },
    {
      "id": "ezk",
      "name": "Ezechiël"
    },
    {
      "id": "dan",
      "name": "Daniël"
    },
    {
      "id": "hos",
      "name": "Hosea"
    },
    {
      "id": "jol",
      "name": "Joël"
    },
    {
      "id": "amo",
      "name": "Amos"
    },
    {
      "id": "oba",
      "name": "Obadja"
    },
    {
      "id": "jon",
      "name": "Jona"
    },
    {
      "id": "mic",
      "name": "Micha"
    },
    {
      "id": "nam",
      "name": "Nahum"
    },
    {
      "id": "hab",
      "name": "Habakuk"
    },
    {
      "id": "zep",
      "name": "Zefanja"
    },
    {
      "id": "hag",
      "name": "Haggai"
    },
    {
      "id": "zec",
      "name": "Zacharia"
    },
    {
      "id": "mal",
      "name": "Maleachi"
    },
    {
      "id": "mat",
      "name": "Mattheüs"
    },
    {
      "id": "mrk",
      "name": "Marcus"
    },
    {
      "id": "luk",
      "name": "Lucas"
    },
    {
      "id": "jhn",
      "name": "Johannes"
    },
    {
      "id": "act",
      "name": "Handelingen"
    },
    {
      "id": "rom",
      "name": "Romeinen"
    },
    {
      "id": "1co",
      "name": "1 Korinthiërs"
    },
    {
      "id": "2co",
      "name": "2 Korinthiërs"
    },
    {
      "id": "gal",
      "name": "Galaten"
    },
    {
      "id": "eph",
      "name": "Efeziërs"
    },
    {
      "id": "php",
      "name": "Filippenzen"
    },
    {
      "id": "col",
      "name": "Colossenzen"
    },
    {
      "id": "1th",
      "name": "1 Thessalonicenzen"
    },
    {
      "id": "2th",
      "name": "2 Thessalonicenzen"
    },
    {
      "id": "1ti",
      "name": "1 Timotheüs"
    },
    {
      "id": "2ti",
      "name": "2 Timotheüs"
    },
    {
      "id": "tit",
      "name": "Titus"
    },
    {
      "id": "phm",
      "name": "Filemon"
    },
    {
      "id": "heb",
      "name": "Hebreeën"
    },
    {
      "id": "jas",
      "name": "Jakobus"
    },
    {
      "id": "1pe",
      "name": "1 Petrus"
    },
    {
      "id": "2pe",
      "name": "2 Petrus"
    },
    {
      "id": "1jn",
      "name": "1 Johannes"
    },
    {
      "id": "2jn",
      "name": "2 Johannes"
    },
    {
      "id": "3jn",
      "name": "3 Johannes"
    },
    {
      "id": "jud",
      "name": "Judas"
    },
    {
      "id": "rev",
      "name": "Openbaring"
    }
  ],
  "default_version": 75,
  "language": {
    "id": "nld",
    "name": "Nederlands"
  },
  "versions": [
    {
      "full_name": "Het Boek",
      "id": 75,
      "name": "HTB"
    },
    {
      "full_name": "Statenvertaling Jongbloed-editie",
      "id": 165,
      "name": "SV-RJ"
    },
    {
      "full_name": "NBG-vertaling 1951",
      "id": 328,
      "name": "NBG51"
    },
    {
      "full_name": "BasisBijbel",
      "id": 1276,
      "name": "BB"
    },
    {
      "full_name": "Herziene Statenvertaling",
      "id": 1990,
      "name": "HSV"
    },
    {
      "full_name": "De Heilige Schrift, Petrus Canisiusvertaling, 1939",
      "id": 2307,
      "name": "NLD1939"
    }
  ]
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-kor.json
{
  "books": [
    {
      "id": "gen",
      "name": "창세기"
    },
    {
      "id": "exo",
      "name": "출애굽기"
    },
    {
      "id": "lev",
      "name": "레위기"
    },
    {
      "id": "num",
      "name": "민수기"
    },
    {
      "id": "deu",
      "name": "신명기"
    },
    {
      "id": "jos",
      "name": "여호수아"
    },
    {
      "id": "jdg",
      "name": "사사기"
    },
    {
      "id": "rut",
      "name": "룻기"
    },
    {
      "id": "1sa",
      "name": "사무엘상"
    },
    {
      "id": "2sa",
      "name": "사무엘하"
    },
    {
      "id": "1ki",
      "name": "열왕기상"
    },
    {
      "id": "2ki",
      "name": "열왕기하"
    },
    {
      "id": "1ch",
      "name": "역대상"
    },
    {
      "id": "2ch",
      "name": "역대하"
    },
    {
      "id": "ezr",
      "name": "에스라"
    },
    {
      "id": "neh",
      "name": "느헤미야"
    },
    {
      "id": "est",
      "name": "에스더"
    },
    {
      "id": "job",
      "name": "욥기"
    },
    {
      "id": "psa",
      "name": "시편"
    },
    {
      "id": "pro",
      "name": "잠언"
    },
    {
      "id": "ecc",
      "name": "전도서"
    },
    {
      "id": "sng",
      "name": "아가"
    },
    {
      "id": "isa",
      "name": "이사야"
    },
    {
      "id": "jer",
      "name": "예레미야"
    },
    {
      "id": "lam",
      "name": "예레미야애가"
    },
    {
      "id": "ezk",
      "name": "에스겔"
    },
    {
      "id": "dan",
      "name": "다니엘"
    },
    {
      "id": "hos",
      "name": "호세아"
    },
    {
      "id": "jol",
      "name": "요엘"
    },
    {
      "id": "amo",
      "name": "아모스"
    },
    {
      "id": "oba",
      "name": "오바댜"
    },
    {
      "id": "jon",
      "name": "요나"
    },
    {
      "id": "mic",
      "name": "미가"
    },
    {
      "id": "nam",
      "name": "나훔"
    },
    {
      "id": "hab",
      "name": "하박국"
    },
    {
      "id": "zep",
      "name": "스바냐"
    },
    {
      "id": "hag",
      "name": "학개"
    },
    {
      "id": "zec",
      "name": "스가랴"
    },
    {
      "id": "mal",
      "name": "말라기"
    },
    {
      "id": "mat",
      "name": "마태복음"
    },
    {
      "id": "mrk",
      "name": "마가복음"
    },
    {
      "id": "luk",
      "name": "누가복음"
    },
    {
      "id": "jhn",
      "name": "요한복음"
    },
    {
      "id": "act",
      "name": "사도행전"
    },
    {
      "id": "rom",
      "name": "로마서"
    },
    {
      "id": "1co",
      "name": "고린도전서"
    },
    {
      "id": "2co",
      "name": "고린도후서"
    },
    {
      "id": "gal",
      "name": "갈라디아서"
    },
    {
      "id": "eph",
      "name": "에베소서"
    },
    {
      "id": "php",
      "name": "빌립보서"
    },
    {
      "id": "col",
      "name": "골로새서"
    },
    {
      "id": "1th",
      "name": "데살로니가전서"
    },
    {
      "id": "2th",
      "name": "데살로니가후서"
    },
    {
      "id": "1ti",
      "name": "디모데전서"
    },
    {
      "id": "2ti",
      "name": "디모데후서"
    },
    {
      "id": "tit",
      "name": "디도서"
    },
    {
      "id": "phm",
      "name": "빌레몬서"
    },
    {
      "id": "heb",
      "name": "히브리서"
    },
    {
      "id": "jas",
      "name": "야고보서"
    },
    {
      "id": "1pe",
      "name": "베드로전서"
    },
    {
      "id": "2pe",
      "name": "베드로후서"
    },
    {
      "id": "1jn",
      "name": "요한일서"
    },
    {
      "id": "2jn",
      "name": "요한이서"
    },
    {
      "id": "3jn",
      "name": "요한삼서"
    },
    {
      "id": "jud",
      "name": "유다서"
    },
    {
      "id": "rev",
      "name": "요한계시록"
    }
  ],
  "default_version": 86,
  "language": {
    "id": "kor",
    "name": "한국어"
  },
  "versions": [
    {
      "full_name": "현대인의 성경",
      "id": 86,
      "name": "KLB"
    },
    {
      "full_name": "개역한글",
      "id": 88,
      "name": "KRV"
    },
    {
      "full_name": "새번역",
      "id": 142,
      "name": "RNKSV"
    }
  ]
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-fra.json
{
  "books": [
    {
      "id": "gen",
      "name": "Genèse"
    },
    {
      "id": "exo",
      "name": "Exode"
    },
    {
      "id": "lev",
      "name": "Lévitique"
    },
    {
      "id": "num",
      "name": "Nombres"
    },
    {
      "id": "deu",
      "name": "Deutéronome"
    },
    {
      "id": "jos",
      "name": "Josué"
    },
    {
      "id": "jdg",
      "name": "Juges"
    },
    {
      "id": "rut",
      "name": "Ruth"
    },
    {
      "id": "1sa",
      "name": "1 Samuel"
    },
    {
      "id": "2sa",
      "name": "2 Samuel"
    },
    {
      "id": "1ki",
      "name": "1 Rois"
    },
    {
      "id": "2ki",
      "name": "2 Rois"
    },
    {
      "id": "1ch",
      "name": "1 Chroniques"
    },
    {
      "id": "2ch",
      "name": "2 Chroniques"
    },
    {
      "id": "ezr",
      "name": "Esdras"
    },
    {
      "id": "neh",
      "name": "Néhémie"
    },
    {
      "id": "est",
      "name": "Esther"
    },
    {
      "id": "job",
      "name": "Job"
    },
    {
      "id": "psa",
      "name": "Psaumes"
    },
    {
      "id": "pro",
      "name": "Proverbes"
    },
    {
      "id": "ecc",
      "name": "Ecclésiaste"
    },
    {
      "id": "sng",
      "name": "Cantiques"
    },
    {
      "id": "isa",
      "name": "Esaïe"
    },
    {
      "id": "jer",
      "name": "Jérémie"
    },
    {
      "id": "lam",
      "name": "Lamentations"
    },
    {
      "id": "ezk",
      "name": "Ezéchiel"
    },
    {
      "id": "dan",
      "name": "Daniel"
    },
    {
      "id": "hos",
      "name": "Osée"
    },
    {
      "id": "jol",
      "name": "Joël"
    },
    {
      "id": "amo",
      "name": "Amos"
    },
    {
      "id": "oba",
      "name": "Abdias"
    },
    {
      "id": "jon",
      "name": "Jonas"
    },
    {
      "id": "mic",
      "name": "Michée"
    },
    {
      "id": "nam",
      "name": "Nahoum"
    },
    {
      "id": "hab",
      "name": "Habaquq"
    },
    {
      "id": "zep",
      "name": "Sophonie"
    },
    {
      "id": "hag",
      "name": "Aggée"
    },
    {
      "id": "zec",
      "name": "Zacharie"
    },
    {
      "id": "mal",
      "name": "Malachie"
    },
    {
      "id": "mat",
      "name": "Matthieu"
    },
    {
      "id": "mrk",
      "name": "Marc"
    },
    {
      "id": "luk",
      "name": "Luc"
    },
    {
      "id": "jhn",
      "name": "Jean"
    },
    {
      "id": "act",
      "name": "Actes"
    },
    {
      "id": "rom",
      "name": "Romains"
    },
    {
      "id": "1co",
      "name": "1 Corinthiens"
    },
    {
      "id": "2co",
      "name": "2 Corinthiens"
    },
    {
      "id": "gal",
      "name": "Galates"
    },
    {
      "id": "eph",
      "name": "Ephésiens"
    },
    {
      "id": "php",
      "name": "Philippiens"
    },
    {
      "id": "col",
      "name": "Colossiens"
    },
    {
      "id": "1th",
      "name": "1 Thessaloniciens"
    },
    {
      "id": "2th",
      "name": "2 Thessaloniciens"
    },
    {
      "id": "1ti",
      "name": "1 Timothée"
    },
    {
      "id": "2ti",
      "name": "2 Timothée"
    },
    {
      "id": "tit",
      "name": "Tite"
    },
    {
      "id": "phm",
      "name": "Philémon"
    },
    {
      "id": "heb",
      "name": "Hébreux"
    },
    {
      "id": "jas",
      "name": "Jacques"
    },
    {
      "id": "1pe",
      "name": "1 Pierre"
    },
    {
      "id": "2pe",
      "name": "2 Pierre"
    },
    {
      "id": "1jn",
      "name": "1 Jean"
    },
    {
      "id": "2jn",
      "name": "2 Jean"
    },
    {
      "id": "3jn",
      "name": "3 Jean"
    },
    {
      "id": "jud",
      "name": "Jude"
    },
    {
      "id": "rev",
      "name": "Apocalypse"
    }
  ],
  "default_version": 21,
  "language": {
    "id": "fra",
    "name": "Français"
  },
  "versions": [
    {
      "full_name": "La Bible du Semeur 2015",
      "id": 21,
      "name": "BDS"
    },
    {
      "full_name": "Martin 1744",
      "id": 62,
      "name": "FMAR"
    },
    {
      "full_name": "Bible en français courant",
      "id": 63,
      "name": "BFC"
    },
    {
      "full_name": "Bible Darby en français",
      "id": 64,
      "name": "FRDBY"
    },
    {
      "full_name": "La Sainte Bible par Louis Segond 1910",
      "id": 93,
      "name": "LSG"
    },
    {
      "full_name": "Nouvelle Bible Segond",
      "id": 104,
      "name": "NBS"
    },
    {
      "full_name": "Nouvelle Edition de Genève 1979",
      "id": 106,
      "name": "NEG79"
    },
    {
      "full_name": "Ostervald",
      "id": 131,
      "name": "OST"
    },
    {
      "full_name": "Parole de Vie 2017",
      "id": 133,
      "name": "PDV2017"
    },
    {
      "full_name": "Bible Segond 21",
      "id": 152,
      "name": "S21"
    },
    {
      "full_name": "Bible catholique Crampon 1923",
      "id": 504,
      "name": "BCC1923"
    },
    {
      "full_name": "Nouvelle Segond révisée",
      "id": 2053,
      "name": "NVS78P"
    },
    {
      "full_name": "Nouvelle Français courant",
      "id": 2367,
      "name": "NFC"
    },
    {
      "full_name": "Évangile de Saint Matthieu 1855 (de Sacy)",
      "id": 2599,
      "name": "SACY"
    }
  ]
}
