=== raycast/extensions/extensions/youversion-suggest/assets/data/schemas/schema-bible.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Bible data for a specific language",
  "type": "object",
  "properties": {
    "books": {
      "description": "The list of Bible books available in this language",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "The ID used by YouVersion to uniquely identify this book",
            "type": "string",
            "pattern": "^([a-z]{3}|[1-3][a-z]{2})$"
          },
          "name": {
            "description": "The name of this book in the respective language",
            "type": "string"
          }
        },
        "required": ["id", "name"],
        "additionalProperties": false
      }
    },
    "language": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The ISO 639-3 code for this language",
          "type": "string",
          "pattern": "^[a-z]{3}(_[a-z]{2,3})?$"
        },
        "name": {
          "description": "The name of this language as written in said language",
          "type": "string"
        }
      }
    },
    "default_version": {
      "description": "The default Bible version to use for this language",
      "type": "integer",
      "minimum": 1
    },
    "versions": {
      "description": "The list of Bible versions for this language",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "full_name": {
            "description": "The full, unabbreviated name of this version",
            "type": "string"
          },
          "id": {
            "description": "The ID used by YouVersion to uniquely identify this version",
            "type": "integer",
            "minimum": 1
          },
          "name": {
            "description": "The acronym for this version",
            "type": "string"
          }
        },
        "required": ["id", "name"],
        "additionalProperties": false
      }
    }
  },
  "required": ["books", "default_version", "versions"],
  "additionalProperties": false
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-hin.json
{
  "books": [
    {
      "id": "gen",
      "name": "उत्पत्ति"
    },
    {
      "id": "exo",
      "name": "निर्गमन"
    },
    {
      "id": "lev",
      "name": "लैव्यवस्था"
    },
    {
      "id": "num",
      "name": "गिनती"
    },
    {
      "id": "deu",
      "name": "व्यवस्थाविवरण"
    },
    {
      "id": "jos",
      "name": "यहोशू"
    },
    {
      "id": "jdg",
      "name": "न्यायियों"
    },
    {
      "id": "rut",
      "name": "रूत"
    },
    {
      "id": "1sa",
      "name": "1 शमूएल"
    },
    {
      "id": "2sa",
      "name": "2 शमूएल"
    },
    {
      "id": "1ki",
      "name": "1 राजा"
    },
    {
      "id": "2ki",
      "name": "2 राजा"
    },
    {
      "id": "1ch",
      "name": "1 इतिहास"
    },
    {
      "id": "2ch",
      "name": "2 इतिहास"
    },
    {
      "id": "ezr",
      "name": "एज्रा"
    },
    {
      "id": "neh",
      "name": "नहेमायाह"
    },
    {
      "id": "est",
      "name": "एस्तेर"
    },
    {
      "id": "job",
      "name": "अय्यूब"
    },
    {
      "id": "psa",
      "name": "भजन संहिता"
    },
    {
      "id": "pro",
      "name": "नीतिवचन"
    },
    {
      "id": "ecc",
      "name": "सभोपदेशक"
    },
    {
      "id": "sng",
      "name": "श्रेष्ठगीत"
    },
    {
      "id": "isa",
      "name": "यशायाह"
    },
    {
      "id": "jer",
      "name": "यिर्मयाह"
    },
    {
      "id": "lam",
      "name": "विलापगीत"
    },
    {
      "id": "ezk",
      "name": "यहेजकेल"
    },
    {
      "id": "dan",
      "name": "दानिय्येल"
    },
    {
      "id": "hos",
      "name": "होशे"
    },
    {
      "id": "jol",
      "name": "योएल"
    },
    {
      "id": "amo",
      "name": "आमोस"
    },
    {
      "id": "oba",
      "name": "ओबद्दाह"
    },
    {
      "id": "jon",
      "name": "योना"
    },
    {
      "id": "mic",
      "name": "मीका"
    },
    {
      "id": "nam",
      "name": "नहूम"
    },
    {
      "id": "hab",
      "name": "हबक्कूक"
    },
    {
      "id": "zep",
      "name": "सपन्याह"
    },
    {
      "id": "hag",
      "name": "हाग्गै"
    },
    {
      "id": "zec",
      "name": "जकर्याह"
    },
    {
      "id": "mal",
      "name": "मलाकी"
    },
    {
      "id": "mat",
      "name": "मत्ती"
    },
    {
      "id": "mrk",
      "name": "मरकुस"
    },
    {
      "id": "luk",
      "name": "लूका"
    },
    {
      "id": "jhn",
      "name": "यूहन्ना"
    },
    {
      "id": "act",
      "name": "प्रेरितों के काम"
    },
    {
      "id": "rom",
      "name": "रोमियो"
    },
    {
      "id": "1co",
      "name": "1 कुरिन्थियों"
    },
    {
      "id": "2co",
      "name": "2 कुरिन्थियों"
    },
    {
      "id": "gal",
      "name": "गलातियों"
    },
    {
      "id": "eph",
      "name": "इफिसियों"
    },
    {
      "id": "php",
      "name": "फिलिप्पियों"
    },
    {
      "id": "col",
      "name": "कुलुस्सियों"
    },
    {
      "id": "1th",
      "name": "1 थिस्सलुनीकियों"
    },
    {
      "id": "2th",
      "name": "2 थिस्सलुनीकियों"
    },
    {
      "id": "1ti",
      "name": "1 तीमुथियुस"
    },
    {
      "id": "2ti",
      "name": "2 तीमुथियुस"
    },
    {
      "id": "tit",
      "name": "तीतुस"
    },
    {
      "id": "phm",
      "name": "फिलेमोन"
    },
    {
      "id": "heb",
      "name": "इब्रानियों"
    },
    {
      "id": "jas",
      "name": "याकूब"
    },
    {
      "id": "1pe",
      "name": "1 पतरस"
    },
    {
      "id": "2pe",
      "name": "2 पतरस"
    },
    {
      "id": "1jn",
      "name": "1 यूहन्ना"
    },
    {
      "id": "2jn",
      "name": "2 यूहन्ना"
    },
    {
      "id": "3jn",
      "name": "3 यूहन्ना"
    },
    {
      "id": "jud",
      "name": "यहूदा"
    },
    {
      "id": "rev",
      "name": "प्रकाशित वाक्य"
    }
  ],
  "default_version": 819,
  "language": {
    "id": "hin",
    "name": "हिन्दी"
  },
  "versions": [
    {
      "full_name": "Hindi Holy Bible",
      "id": 819,
      "name": "HHBD"
    },
    {
      "full_name": "सरल हिन्दी बाइबल",
      "id": 1628,
      "name": "HSS"
    },
    {
      "full_name": "पवित्र बाइबिल CL Bible (BSI)",
      "id": 1682,
      "name": "HINCLBSI"
    },
    {
      "full_name": "पवित्र बाइबिल OV (Re-edited) Bible (BSI)",
      "id": 1683,
      "name": "HINOVBSI"
    },
    {
      "full_name": "नया नियम",
      "id": 1953,
      "name": "HIN2017"
    },
    {
      "full_name": "इंडियन रिवाइज्ड वर्जन (IRV) हिंदी - 2019",
      "id": 1980,
      "name": "IRVHIN"
    },
    {
      "full_name": "पवित्र बाइबल",
      "id": 2562,
      "name": "HERV"
    }
  ]
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-jpn.json
{
  "books": [
    {
      "id": "gen",
      "name": "創世記"
    },
    {
      "id": "exo",
      "name": "出エジプト記"
    },
    {
      "id": "lev",
      "name": "レビ記"
    },
    {
      "id": "num",
      "name": "民数記"
    },
    {
      "id": "deu",
      "name": "申命記"
    },
    {
      "id": "jos",
      "name": "ヨシュア記"
    },
    {
      "id": "jdg",
      "name": "士師記"
    },
    {
      "id": "rut",
      "name": "ルツ記"
    },
    {
      "id": "1sa",
      "name": "サムエル記上"
    },
    {
      "id": "2sa",
      "name": "サムエル記下"
    },
    {
      "id": "1ki",
      "name": "列王紀上"
    },
    {
      "id": "2ki",
      "name": "列王紀下"
    },
    {
      "id": "1ch",
      "name": "歴代志上"
    },
    {
      "id": "2ch",
      "name": "歴代志下"
    },
    {
      "id": "ezr",
      "name": "エズラ記"
    },
    {
      "id": "neh",
      "name": "ネヘミヤ記"
    },
    {
      "id": "est",
      "name": "エステル記"
    },
    {
      "id": "job",
      "name": "ヨブ記"
    },
    {
      "id": "psa",
      "name": "詩篇"
    },
    {
      "id": "pro",
      "name": "箴言"
    },
    {
      "id": "ecc",
      "name": "伝道の書"
    },
    {
      "id": "sng",
      "name": "雅歌"
    },
    {
      "id": "isa",
      "name": "イザヤ書"
    },
    {
      "id": "jer",
      "name": "エレミヤ書"
    },
    {
      "id": "lam",
      "name": "哀歌"
    },
    {
      "id": "ezk",
      "name": "エゼキエル書"
    },
    {
      "id": "dan",
      "name": "ダニエル書"
    },
    {
      "id": "hos",
      "name": "ホセア書"
    },
    {
      "id": "jol",
      "name": "ヨエル書"
    },
    {
      "id": "amo",
      "name": "アモス書"
    },
    {
      "id": "oba",
      "name": "オバデヤ書"
    },
    {
      "id": "jon",
      "name": "ヨナ書"
    },
    {
      "id": "mic",
      "name": "ミカ書"
    },
    {
      "id": "nam",
      "name": "ナホム書"
    },
    {
      "id": "hab",
      "name": "ハバクク書"
    },
    {
      "id": "zep",
      "name": "ゼパニヤ書"
    },
    {
      "id": "hag",
      "name": "ハガイ書"
    },
    {
      "id": "zec",
      "name": "ゼカリヤ書"
    },
    {
      "id": "mal",
      "name": "マラキ書"
    },
    {
      "id": "mat",
      "name": "マタイによる福音書"
    },
    {
      "id": "mrk",
      "name": "マルコによる福音書"
    },
    {
      "id": "luk",
      "name": "ルカによる福音書"
    },
    {
      "id": "jhn",
      "name": "ヨハネによる福音書"
    },
    {
      "id": "act",
      "name": "使徒行伝"
    },
    {
      "id": "rom",
      "name": "ローマ人への手紙"
    },
    {
      "id": "1co",
      "name": "コリント人への第一の手紙"
    },
    {
      "id": "2co",
      "name": "コリント人への第二の手紙"
    },
    {
      "id": "gal",
      "name": "ガラテヤ人への手紙"
    },
    {
      "id": "eph",
      "name": "エペソ人への手紙"
    },
    {
      "id": "php",
      "name": "ピリピ人への手紙"
    },
    {
      "id": "col",
      "name": "コロサイ人への手紙"
    },
    {
      "id": "1th",
      "name": "テサロニケ人への第一の手紙"
    },
    {
      "id": "2th",
      "name": "テサロニケ人への第二の手紙"
    },
    {
      "id": "1ti",
      "name": "テモテヘの第一の手紙"
    },
    {
      "id": "2ti",
      "name": "テモテヘの第二の手紙"
    },
    {
      "id": "tit",
      "name": "テトスヘの手紙"
    },
    {
      "id": "phm",
      "name": "ピレモンヘの手紙"
    },
    {
      "id": "heb",
      "name": "ヘブル人への手紙"
    },
    {
      "id": "jas",
      "name": "ヤコブの手紙"
    },
    {
      "id": "1pe",
      "name": "ペテロの第一の手紙"
    },
    {
      "id": "2pe",
      "name": "ペテロの第二の手紙"
    },
    {
      "id": "1jn",
      "name": "ヨハネの第一の手紙"
    },
    {
      "id": "2jn",
      "name": "ヨハネの第二の手紙"
    },
    {
      "id": "3jn",
      "name": "ヨハネの第三の手紙"
    },
    {
      "id": "jud",
      "name": "ユダの手紙"
    },
    {
      "id": "rev",
      "name": "ヨハネの黙示録"
    }
  ],
  "default_version": 81,
  "language": {
    "id": "jpn",
    "name": "日本語"
  },
  "versions": [
    {
      "full_name": "Colloquial Japanese (1955)",
      "id": 81,
      "name": "JA1955"
    },
    {
      "full_name": "リビングバイブル",
      "id": 83,
      "name": "JCB"
    },
    {
      "full_name": "Seisho Shinkyoudoyaku 聖書 新共同訳",
      "id": 1819,
      "name": "新共同訳"
    },
    {
      "full_name": "Japanese: 聖書　口語訳",
      "id": 1820,
      "name": "口語訳"
    },
    {
      "full_name": "ALIVEバイブル: 新約聖書",
      "id": 2040,
      "name": "AB"
    }
  ]
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-pol.json
{
  "books": [
    {
      "id": "gen",
      "name": "I Mojżeszowa"
    },
    {
      "id": "exo",
      "name": "II Mojżeszowa"
    },
    {
      "id": "lev",
      "name": "III Mojżeszowa"
    },
    {
      "id": "num",
      "name": "IV Mojżeszowa"
    },
    {
      "id": "deu",
      "name": "V Mojżeszowa"
    },
    {
      "id": "jos",
      "name": "Jozuego"
    },
    {
      "id": "jdg",
      "name": "Sędziów"
    },
    {
      "id": "rut",
      "name": "Rut"
    },
    {
      "id": "1sa",
      "name": "1 Samuelowa"
    },
    {
      "id": "2sa",
      "name": "2 Samuelowa"
    },
    {
      "id": "1ki",
      "name": "1 Królewska"
    },
    {
      "id": "2ki",
      "name": "2 Królewska"
    },
    {
      "id": "1ch",
      "name": "1 Kronik"
    },
    {
      "id": "2ch",
      "name": "2 Kronik"
    },
    {
      "id": "ezr",
      "name": "Ezdrasza"
    },
    {
      "id": "neh",
      "name": "Nehemiasza"
    },
    {
      "id": "est",
      "name": "Estery"
    },
    {
      "id": "job",
      "name": "Joba"
    },
    {
      "id": "psa",
      "name": "Psalmy"
    },
    {
      "id": "pro",
      "name": "Przypowieści Salomonowych"
    },
    {
      "id": "ecc",
      "name": "Kaznodziei Salomonowego"
    },
    {
      "id": "sng",
      "name": "Pieśń nad Pieśniami"
    },
    {
      "id": "isa",
      "name": "Izajasza"
    },
    {
      "id": "jer",
      "name": "Jeremiasza"
    },
    {
      "id": "lam",
      "name": "Treny"
    },
    {
      "id": "ezk",
      "name": "Ezechiela"
    },
    {
      "id": "dan",
      "name": "Daniela"
    },
    {
      "id": "hos",
      "name": "Ozeasza"
    },
    {
      "id": "jol",
      "name": "Joela"
    },
    {
      "id": "amo",
      "name": "Amosa"
    },
    {
      "id": "oba",
      "name": "Abdiasza"
    },
    {
      "id": "jon",
      "name": "Jonasza"
    },
    {
      "id": "mic",
      "name": "Micheasza"
    },
    {
      "id": "nam",
      "name": "Nahuma"
    },
    {
      "id": "hab",
      "name": "Abakuka"
    },
    {
      "id": "zep",
      "name": "Sofoniasza"
    },
    {
      "id": "hag",
      "name": "Aggeusza"
    },
    {
      "id": "zec",
      "name": "Zachariasza"
    },
    {
      "id": "mal",
      "name": "Malachiasza"
    },
    {
      "id": "mat",
      "name": "Ewangelia Mateusza"
    },
    {
      "id": "mrk",
      "name": "Ewangelia Marka"
    },
    {
      "id": "luk",
      "name": "Ewangelia Łukasza"
    },
    {
      "id": "jhn",
      "name": "Ewangelia Jana"
    },
    {
      "id": "act",
      "name": "Dzieje Apostolskie"
    },
    {
      "id": "rom",
      "name": "Rzymian"
    },
    {
      "id": "1co",
      "name": "1 Koryntów"
    },
    {
      "id": "2co",
      "name": "2 Koryntów"
    },
    {
      "id": "gal",
      "name": "Galatów"
    },
    {
      "id": "eph",
      "name": "Efezów"
    },
    {
      "id": "php",
      "name": "Filipensów"
    },
    {
      "id": "col",
      "name": "Kolosensów"
    },
    {
      "id": "1th",
      "name": "1 Tesalonicensów"
    },
    {
      "id": "2th",
      "name": "2 Tesalonicensów"
    },
    {
      "id": "1ti",
      "name": "1 Tymoteusza"
    },
    {
      "id": "2ti",
      "name": "2 Tymoteusza"
    },
    {
      "id": "tit",
      "name": "Tytusa"
    },
    {
      "id": "phm",
      "name": "Filemona"
    },
    {
      "id": "heb",
      "name": "Żydów"
    },
    {
      "id": "jas",
      "name": "Jakuba"
    },
    {
      "id": "1pe",
      "name": "1 Piotra"
    },
    {
      "id": "2pe",
      "name": "2 Piotra"
    },
    {
      "id": "1jn",
      "name": "1 Jana"
    },
    {
      "id": "2jn",
      "name": "2 Jana"
    },
    {
      "id": "3jn",
      "name": "3 Jana"
    },
    {
      "id": "jud",
      "name": "Judy"
    },
    {
      "id": "rev",
      "name": "Objawienie św. Jana"
    }
  ],
  "default_version": 132,
  "language": {
    "id": "pol",
    "name": "Polski"
  },
  "versions": [
    {
      "full_name": "Biblia Gdańska",
      "id": 132,
      "name": "PBG"
    },
    {
      "full_name": "Słowo Życia",
      "id": 137,
      "name": "PLNT"
    },
    {
      "full_name": "UWSPÓŁCZEŚNIONA BIBLIA GDAŃSKA",
      "id": 138,
      "name": "UBG"
    },
    {
      "full_name": "Nowa Biblia Gdańska",
      "id": 319,
      "name": "NBG"
    },
    {
      "full_name": "Biblia, to jest Pismo Święte Starego i Nowego Przymierza Wydanie pierwsze 2018",
      "id": 2095,
      "name": "SNP"
    }
  ]
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-swh.json
{
  "books": [
    {
      "id": "gen",
      "name": "Mwanzo"
    },
    {
      "id": "exo",
      "name": "Kutoka"
    },
    {
      "id": "lev",
      "name": "Walawi"
    },
    {
      "id": "num",
      "name": "Hesabu"
    },
    {
      "id": "deu",
      "name": "Kumbukumbu la Sheria"
    },
    {
      "id": "jos",
      "name": "Yoshua"
    },
    {
      "id": "jdg",
      "name": "Waamuzi"
    },
    {
      "id": "rut",
      "name": "Ruthu"
    },
    {
      "id": "1sa",
      "name": "1 Samueli"
    },
    {
      "id": "2sa",
      "name": "2 Samueli"
    },
    {
      "id": "1ki",
      "name": "1 Wafalme"
    },
    {
      "id": "2ki",
      "name": "2 Wafalme"
    },
    {
      "id": "1ch",
      "name": "1 Mambo ya Nyakati"
    },
    {
      "id": "2ch",
      "name": "2 Mambo ya Nyakati"
    },
    {
      "id": "ezr",
      "name": "Ezra"
    },
    {
      "id": "neh",
      "name": "Nehemia"
    },
    {
      "id": "est",
      "name": "Esta"
    },
    {
      "id": "job",
      "name": "Yobu"
    },
    {
      "id": "psa",
      "name": "Zaburi"
    },
    {
      "id": "pro",
      "name": "Methali"
    },
    {
      "id": "ecc",
      "name": "Mhubiri"
    },
    {
      "id": "sng",
      "name": "Wimbo Ulio Bora"
    },
    {
      "id": "isa",
      "name": "Isaya"
    },
    {
      "id": "jer",
      "name": "Yeremia"
    },
    {
      "id": "lam",
      "name": "Maombolezo"
    },
    {
      "id": "ezk",
      "name": "Ezekieli"
    },
    {
      "id": "dan",
      "name": "Danieli"
    },
    {
      "id": "hos",
      "name": "Hosea"
    },
    {
      "id": "jol",
      "name": "Yoeli"
    },
    {
      "id": "amo",
      "name": "Amosi"
    },
    {
      "id": "oba",
      "name": "Obadia"
    },
    {
      "id": "jon",
      "name": "Yona"
    },
    {
      "id": "mic",
      "name": "Mika"
    },
    {
      "id": "nam",
      "name": "Nahumu"
    },
    {
      "id": "hab",
      "name": "Habakuki"
    },
    {
      "id": "zep",
      "name": "Sefania"
    },
    {
      "id": "hag",
      "name": "Hagai"
    },
    {
      "id": "zec",
      "name": "Zekaria"
    },
    {
      "id": "mal",
      "name": "Malaki"
    },
    {
      "id": "mat",
      "name": "Mathayo"
    },
    {
      "id": "mrk",
      "name": "Marko"
    },
    {
      "id": "luk",
      "name": "Luka"
    },
    {
      "id": "jhn",
      "name": "Yohane"
    },
    {
      "id": "act",
      "name": "Matendo"
    },
    {
      "id": "rom",
      "name": "Waroma"
    },
    {
      "id": "1co",
      "name": "1 Wakorintho"
    },
    {
      "id": "2co",
      "name": "2 Wakorintho"
    },
    {
      "id": "gal",
      "name": "Wagalatia"
    },
    {
      "id": "eph",
      "name": "Waefeso"
    },
    {
      "id": "php",
      "name": "Wafilipi"
    },
    {
      "id": "col",
      "name": "Wakolosai"
    },
    {
      "id": "1th",
      "name": "1 Wathesalonike"
    },
    {
      "id": "2th",
      "name": "2 Wathesalonike"
    },
    {
      "id": "1ti",
      "name": "1 Timotheo"
    },
    {
      "id": "2ti",
      "name": "2 Timotheo"
    },
    {
      "id": "tit",
      "name": "Tito"
    },
    {
      "id": "phm",
      "name": "Filemoni"
    },
    {
      "id": "heb",
      "name": "Waebrania"
    },
    {
      "id": "jas",
      "name": "Yakobo"
    },
    {
      "id": "1pe",
      "name": "1 Petro"
    },
    {
      "id": "2pe",
      "name": "2 Petro"
    },
    {
      "id": "1jn",
      "name": "1 Yohane"
    },
    {
      "id": "2jn",
      "name": "2 Yohane"
    },
    {
      "id": "3jn",
      "name": "3 Yohane"
    },
    {
      "id": "jud",
      "name": "Yuda"
    },
    {
      "id": "rev",
      "name": "Ufunuo"
    }
  ],
  "default_version": 74,
  "language": {
    "id": "swh",
    "name": "Kiswahili"
  },
  "versions": [
    {
      "full_name": "Biblia Habari Njema",
      "id": 74,
      "name": "BHN"
    },
    {
      "full_name": "Maandiko Matakatifu ya Mungu Yaitwayo Biblia",
      "id": 164,
      "name": "SUV"
    },
    {
      "full_name": "Biblia Habari Njema",
      "id": 393,
      "name": "BHND"
    },
    {
      "full_name": "Neno: Bibilia Takatifu 2014",
      "id": 1627,
      "name": "NEN"
    },
    {
      "full_name": "Swahili Revised Union Version",
      "id": 1817,
      "name": "SRUVDC"
    },
    {
      "full_name": "Swahili Revised Union Version",
      "id": 1818,
      "name": "SRUV"
    },
    {
      "full_name": "Biblia Habari Njema: Toleo la Kujifunza",
      "id": 2144,
      "name": "BHNTLK"
    },
    {
      "full_name": "Agano Jipya: Tafsiri ya Kusoma-Kwa-Urahisi",
      "id": 2484,
      "name": "TKU"
    },
    {
      "full_name": "Neno: Maandiko Matakatifu",
      "id": 2729,
      "name": "NMM"
    },
    {
      "full_name": "BIBLIA Yenye Vitabu vya Deuterokanoni HABARI NJEMA",
      "id": 2936,
      "name": "SCLDC10"
    },
    {
      "full_name": "BIBLIA KISWAHILI",
      "id": 2937,
      "name": "RSUVDC"
    },
    {
      "full_name": "New Testament in Swahili (Zanzibar) Revised Edition 1921",
      "id": 3048,
      "name": "SWZZB1921"
    },
    {
      "full_name": "Swahili Roehl Bible 1937",
      "id": 3049,
      "name": "SRB37"
    }
  ]
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-spa_es.json
{
  "books": [
    {
      "id": "gen",
      "name": "GÉNESIS"
    },
    {
      "id": "exo",
      "name": "ÉXODO"
    },
    {
      "id": "lev",
      "name": "LEVÍTICO"
    },
    {
      "id": "num",
      "name": "NÚMEROS"
    },
    {
      "id": "deu",
      "name": "DEUTERONOMIO"
    },
    {
      "id": "jos",
      "name": "JOSUÉ"
    },
    {
      "id": "jdg",
      "name": "JUECES"
    },
    {
      "id": "rut",
      "name": "RUT"
    },
    {
      "id": "1sa",
      "name": "1 SAMUEL"
    },
    {
      "id": "2sa",
      "name": "2 SAMUEL"
    },
    {
      "id": "1ki",
      "name": "1 REYES"
    },
    {
      "id": "2ki",
      "name": "2 REYES"
    },
    {
      "id": "1ch",
      "name": "1 CRÓNICAS"
    },
    {
      "id": "2ch",
      "name": "2 CRÓNICAS"
    },
    {
      "id": "ezr",
      "name": "ESDRAS"
    },
    {
      "id": "neh",
      "name": "NEHEMÍAS"
    },
    {
      "id": "est",
      "name": "ESTER"
    },
    {
      "id": "job",
      "name": "JOB"
    },
    {
      "id": "psa",
      "name": "SALMOS"
    },
    {
      "id": "pro",
      "name": "PROVERBIOS"
    },
    {
      "id": "ecc",
      "name": "ECLESIASTÉS"
    },
    {
      "id": "sng",
      "name": "CANTARES"
    },
    {
      "id": "isa",
      "name": "ISAÍAS"
    },
    {
      "id": "jer",
      "name": "JEREMÍAS"
    },
    {
      "id": "lam",
      "name": "LAMENTACIONES"
    },
    {
      "id": "ezk",
      "name": "EZEQUIEL"
    },
    {
      "id": "dan",
      "name": "DANIEL"
    },
    {
      "id": "hos",
      "name": "OSEAS"
    },
    {
      "id": "jol",
      "name": "JOEL"
    },
    {
      "id": "amo",
      "name": "AMÓS"
    },
    {
      "id": "oba",
      "name": "ABDÍAS"
    },
    {
      "id": "jon",
      "name": "JONÁS"
    },
    {
      "id": "mic",
      "name": "MIQUEAS"
    },
    {
      "id": "nam",
      "name": "NAHÚM"
    },
    {
      "id": "hab",
      "name": "HABACUC"
    },
    {
      "id": "zep",
      "name": "SOFONÍAS"
    },
    {
      "id": "hag",
      "name": "HAGEO"
    },
    {
      "id": "zec",
      "name": "ZACARÍAS"
    },
    {
      "id": "mal",
      "name": "MALAQUÍAS"
    },
    {
      "id": "mat",
      "name": "MATEO"
    },
    {
      "id": "mrk",
      "name": "MARCOS"
    },
    {
      "id": "luk",
      "name": "LUCAS"
    },
    {
      "id": "jhn",
      "name": "JUAN"
    },
    {
      "id": "act",
      "name": "HECHOS"
    },
    {
      "id": "rom",
      "name": "ROMANOS"
    },
    {
      "id": "1co",
      "name": "1 CORINTIOS"
    },
    {
      "id": "2co",
      "name": "2 CORINTIOS"
    },
    {
      "id": "gal",
      "name": "GÁLATAS"
    },
    {
      "id": "eph",
      "name": "EFESIOS"
    },
    {
      "id": "php",
      "name": "FILIPENSES"
    },
    {
      "id": "col",
      "name": "COLOSENSES"
    },
    {
      "id": "1th",
      "name": "1 TESALONICENSES"
    },
    {
      "id": "2th",
      "name": "2 TESALONICENSES"
    },
    {
      "id": "1ti",
      "name": "1 TIMOTEO"
    },
    {
      "id": "2ti",
      "name": "2 TIMOTEO"
    },
    {
      "id": "tit",
      "name": "TITO"
    },
    {
      "id": "phm",
      "name": "FILEMÓN"
    },
    {
      "id": "heb",
      "name": "HEBREOS"
    },
    {
      "id": "jas",
      "name": "SANTIAGO"
    },
    {
      "id": "1pe",
      "name": "1 PEDRO"
    },
    {
      "id": "2pe",
      "name": "2 SAN PEDRO"
    },
    {
      "id": "1jn",
      "name": "1 JUAN"
    },
    {
      "id": "2jn",
      "name": "2 JUAN"
    },
    {
      "id": "3jn",
      "name": "3 JUAN"
    },
    {
      "id": "jud",
      "name": "JUDAS"
    },
    {
      "id": "rev",
      "name": "APOCALIPSIS"
    }
  ],
  "default_version": 53,
  "language": {
    "id": "spa_es",
    "name": "Español (España)"
  },
  "versions": [
    {
      "full_name": "Dios Habla Hoy Versión Española",
      "id": 53,
      "name": "DHHE"
    },
    {
      "full_name": "La Biblia de las Américas",
      "id": 89,
      "name": "LBLA"
    },
    {
      "full_name": "Reina-Valera Antigua",
      "id": 147,
      "name": "RVES"
    },
    {
      "full_name": "Biblia Reina Valera 1960",
      "id": 149,
      "name": "RVR1960"
    },
    {
      "full_name": "Biblia Reina Valera 1995",
      "id": 150,
      "name": "RVR95"
    },
    {
      "full_name": "La Palabra (versión española)",
      "id": 210,
      "name": "BLP"
    },
    {
      "full_name": "La Biblia, Traducción Interconfesional (versión española)",
      "id": 214,
      "name": "BTI"
    },
    {
      "full_name": "Dios Habla Hoy Con Deuterocanónicos Versión Española",
      "id": 442,
      "name": "DHHED"
    },
    {
      "full_name": "Nueva Versión Internacional - Castellano",
      "id": 1637,
      "name": "NVI"
    },
    {
      "full_name": "Biblia del Oso 1573",
      "id": 1715,
      "name": "BDO1573"
    }
  ]
}
